name: Publish to PYPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pauron
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Build package
      run: uv sync && uv build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
