name: Update k3sup AUR package

on:
  workflow_dispatch:
    inputs:
      pkg_name:
        description: "AUR package name for the updates"
        required: true
        default: "k3sup"
        type: string

jobs:
  update-k3sup-aur:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install requests

      - name: Test SSH setup manually
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
        run: |
          # Create SSH directory
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Write SSH key
          echo "$AUR_SSH_KEY" > ~/.ssh/aur_key
          chmod 600 ~/.ssh/aur_key

          # Check if key file exists and has content
          ls -la ~/.ssh/
          echo "Key file size: $(wc -c < ~/.ssh/aur_key) bytes"

          # Test SSH connection manually
          ssh -i ~/.ssh/aur_key -o StrictHostKeyChecking=no -T aur@aur.archlinux.org || echo "SSH test completed (exit code: $?)"

      - name: Update AUR package
        env:
          AUR_SSH_KEY: ${{ secrets.AUR_SSH_KEY }}
        run: |
          python main.py -p ${{ github.event.inputs.pkg_name }}
  
  
